### ISSUE TITLE
[Question] Migrate to oauth2 crate

### ISSUE THREAD

**Issue by tyranron** [kstep/vkrs#64]
Thank you for you crate!

This crate currently is built on top of [inth-oauth2](https://crates.io/crates/inth-oauth2) crate which on its latest version 0.15.0 (unstable, though) still [hardcodes `response_type` to be `code`](https://github.com/programble/inth-oauth2/blob/v0.15.0/src/client/mod.rs#L93).

However, there is another [oauth2](https://crates.io/crates/oauth2) crate which is considered to be stable and has more wide support of OAuth2 features (`response_type=token` too). It's also belongs to [Alex Crichton](https://github.com/alexcrichton) (so has high guarantees of supporting/evolving and being Rust'ish asap).

Supporting `response_type=token` is quite necessary for VK API client, as only such type of tokens [allows to use extended API methods](https://vk.com/dev/oauth_dialog):

> Примечание
> * Если Вы разрабатываете Standalone-приложение и параметр response_type = "token", то в качестве параметра redirect_uri необходимо указывать адрес https://oauth.vk.com/blank.html, на который будут переданы данные авторизации. Обратите внимание, что только в данном случае у Вас будет возможность использовать расширенные методы работы с API.

P.S. Is this crate currently abandoned?

**Comment by kstep** [comment]
More or less. I'm a little distracted from active Rust development now, but I happily accept PRs.

**Comment by kstep** [comment]
A lot of dependencies should be updated, along with newer Rust features support. I don't have enough free time to work on VKRS any more, so if you want to help, I will happily accept your PRs! Thank you!

**Comment by tyranron** [comment]
@kstep I'm relatively new to Rust and don't feel myself mature enough. Can't promise anything in short term, but I'll sent PRs probably, as I need this lib for my side projects.

**Comment by kstep** [comment]
`oauth2` has an external dependency on curl, which I'd like to avoid.
